function [varargout] = VariationRigidPendulum(varargin)
%% 
% This function was generated by the Scala: Dynamics on Manifold package
% Wed Jun 24 14:25:14 PDT 2020
% 
% NOTE: This function makes use of geometric-toolbox
% 		 link: https://github.com/HybridRobotics/geometric-toolbox
%%


%% Function Inputs
params = varargin{1};

%% 
A = -[(g)*((m)*((hat(rho))*(((-1.0))*(hat(((-1.0))*((transpose(R))*(e3))))))),(((hat(Omega_R))*(J))+(((-1.0))*(hat((J)*(Omega_R))))),;
];

B = -[((-1.0))*(eye(3)),;
];




%% Outputs
varargout{1} = A;
varargout{1} = B;

end