function [varargout] = VariationMultipleQuadrotorRigidPayload(varargin)
%% 
% This function was generated by the Scala: Dynamics on Manifold package
% Wed Jun 24 18:12:52 PDT 2020
% 
% NOTE: This function makes use of geometric-toolbox
% 		 link: https://github.com/HybridRobotics/geometric-toolbox
%%


%% Function Inputs
params = varargin{1};

%% 
A = -[(((-1.0))*(m_i))*(((q_i)*(transpose((transpose(R_L))*(q_i))))*(hat(r_i))),((((((((dot(q_i,(m_i)*(((ddx_L)+((g)*(e_3))))))*(eye(3)))*(((-1.0))*(hat(q_i))))+(((q_i)*(transpose((m_i)*(((ddx_L)+((g)*(e_3)))))))*(((-1.0))*(hat(q_i))))))+(((((dot((transpose(R_L))*(q_i),(hat(r_i))*((((-1.0))*(m_i))*(dOmega_R_L))))*(eye(3)))*(((-1.0))*(hat(q_i))))+(((q_i)*(transpose((hat(r_i))*((((-1.0))*(m_i))*(dOmega_R_L)))))*((transpose(R_L))*(((-1.0))*(hat(q_i)))))))))+(((-1.0))*(((((((dot(q_i,(m_i)*((l_i)*((fracf_im_il_i)*((R_i)*(e_3))))))*(eye(3)))*(((-1.0))*(hat(q_i))))+(((q_i)*(transpose((m_i)*((l_i)*((fracf_im_il_i)*((R_i)*(e_3)))))))*(((-1.0))*(hat(q_i))))))+((((((m_i)*(((-1.0))*(q_i)))*(transpose(((hat(Omega_R_L))*(hat(Omega_R_L)))*(r_i))))*((transpose(R_L))*(((-1.0))*(hat(q_i)))))+((((-1.0))*((((dot((transpose(R_L))*(q_i),((hat(Omega_R_L))*(hat(Omega_R_L)))*(r_i)))+((dot(omega_q_i,omega_q_i))*(l_i))))*(m_i)))*(((-1.0))*(hat(q_i)))))))))),((-1.0))*(((2.0))*(((l_i)*((m_i)*(((-1.0))*(q_i))))*(transpose(omega_q_i)))),((-1.0))*(((l_i)*((m_i)*((q_i)*(transpose(q_i)))))*((fracf_im_il_i)*((R_i)*(((-1.0))*(hat(e_3)))))),((((q_i)*(transpose((hat(r_i))*((((-1.0))*(m_i))*(dOmega_R_L)))))*(((-1.0))*(hat(((-1.0))*((transpose(R_L))*(q_i))))))+(((-1.0))*((((m_i)*(((-1.0))*(q_i)))*(transpose(((hat(Omega_R_L))*(hat(Omega_R_L)))*(r_i))))*(((-1.0))*(hat(((-1.0))*((transpose(R_L))*(q_i)))))))),((-1.0))*((((m_i)*(((-1.0))*(q_i)))*(transpose((transpose(R_L))*(q_i))))*((((hat(Omega_R_L))*(((-1.0))*(hat(r_i))))+(((-1.0))*(hat((hat(Omega_R_L))*(r_i))))))),;
];

B = -[;
];




%% Outputs
varargout{1} = A;
varargout{1} = B;

end